### ISSUE TITLE
Alternative boxes for different providers

### ISSUE THREAD

**Issue by MekDrop** [ImpressCMS/vagrant-impressbox#44]
It would be awesome, that config files can have list of alternative boxes if specified box doesn't have required provider.

How this could look in config.yaml file:
```yaml
box:
   virtualbox: gbarbieru/xenial
   parallels: boxcutter/ubuntu1604
   libvirt: yk0/ubuntu-xenial
```
